services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_app
    restart: always
    environment:
      - HTTP_PROXY=http://warp:1080
      - HTTPS_PROXY=http://warp:1080
    volumes:
      - .:/app
      - ./downloads:/app/downloads
    depends_on:
      - warp
    networks:
      - app-network

  warp:
    image: caomingjun/warp
    container_name: warp
    restart: always
    ports:
      - '1080:1080'
    environment:
      - WARP_SLEEP=2
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./data:/var/lib/cloudflare-warp
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
